sudo: required
language: ruby
services:
  - docker
stages:
  - compile
  - name: publish
    if: branch = master OR branch = development OR tag IS present
install:
  - docker pull toxicbakery/alpine-glibc-android:latest
  - bash .travis.before_script.sh
jobs:
  include:
    - stage: compile
      script: ./.travis.compile.sh
    - stage: publish
      script: ./.travis.publish.sh
  email:
    - toxicbakery@gmail.com