
version: 2
jobs:
  build:
    docker:
      - image: cimg/android:2022.09
    steps:
      - checkout
      - run:
          name: Execute Gradle
          command: |
            ./gradlew build
            if [ "master" = "$CIRCLE_BRANCH" ] || [ ! -z "$CIRCLE_TAG" ]; then
              echo "signing.keyId=${SIGNING_KEY}" >> "gradle.properties"
              echo "signing.password=${SIGNING_PASSWORD}" >> "gradle.properties"
              echo "signing.secretKeyRingFile=../maven.keystore" >> "gradle.properties"
              gpg --cipher-algo AES256 --yes --batch --passphrase=$ENC_FILE_KEY maven.keystore.gpg
              ./gradlew uploadArchives
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Sonatype
          filters:
            tags:
              only: /.*/
